### ISSUE TITLE
Versioned Docker image

### ISSUE THREAD

**Issue by jangrewe** [Technofy/cloudwatch_exporter#2]
Hi, could you please provide a versioned/tagged image via the official Docker hub?

Thanks in advance!

**Comment by a-teisseire** [comment]
Hello, I have added this on our TODO list, in the meantime we're waiting for the DockerHub support on some case, once everything is sorted out, I will get back to you.
Thanks for your interest in our project!

**Comment by a-teisseire** [comment]
Hello,
We have pushed the master on the Docker Hub. It's been tagged as master.
https://hub.docker.com/r/technofy/cloudwatch_exporter/

Let us know if you have any other remarks.

**Comment by jangrewe** [comment]
Thanks! I originally meant something with semantic versioning, so that you don't accidentally upgrade to an incompatible image, but i guess the risk is rather low at the moment... ;-)

Speaking of which, any chance to get the dimension select by regex anytime soon? The random IDs added to Network ELB names make it pretty much impossible to configure the exporter for multiple environments. =(

**Comment by a-teisseire** [comment]
I'll submit some changes to integrate dimension_select_regex very soon, at the same time, I'll push a new docker image with a version number ;)

**Comment by jangrewe** [comment]
Yay, thanks in advance! =)

**Comment by hairyhenderson** [comment]
Any chance of making this happen @a-teisseire? At least, an update for the latest changes would be useful 😀

**Comment by fas3r** [comment]
Hello @a-teisseire , that would be nice :)
